import { QuestionBank, SoundEffect } from './types';

export const PRIZE_LADDER = [
  "1.000.000", "2.000.000", "4.000.000", "6.000.000", 
  "10.000.000", "15.000.000", "25.000.000", "35.000.000", 
  "50.000.000", "70.000.000", "85.000.000", "100.000.000"
];

// Reusing and expanding the provided question bank
export const QUESTION_BANK: QuestionBank = {
  1: [
      { id: "1-1", q: "CLB nào có biệt danh là 'The Gunners'?", a: ["Chelsea", "Man Utd", "Arsenal", "Tottenham"], c: 2, p: "1" },
      { id: "1-2", q: "Quỷ đỏ là biệt danh của CLB nào?", a: ["Liverpool", "Man Utd", "Everton", "Leicester"], c: 1, p: "1" },
      { id: "1-3", q: "Màu áo truyền thống của Chelsea là màu gì?", a: ["Đỏ", "Trắng", "Xanh dương", "Vàng"], c: 2, p: "1" },
      { id: "1-4", q: "Sân vận động Anfield là của đội nào?", a: ["Liverpool", "Man City", "Arsenal", "Chelsea"], c: 0, p: "1" },
      { id: "1-5", q: "Trong bóng đá, vị trí 'GK' là viết tắt của?", a: ["Hậu vệ", "Thủ môn", "Tiền đạo", "Tiền vệ"], c: 1, p: "1" },
      { id: "1-6", q: "Cầu thủ ghi nhiều bàn nhất một mùa giải 38 trận (36 bàn)?", a: ["Salah", "Haaland", "Kane", "Shearer"], c: 1, p: "1" },
      { id: "1-7", q: "Trọng tài dùng thẻ gì để cảnh cáo (phạt nhẹ) cầu thủ?", a: ["Thẻ xanh", "Thẻ đỏ", "Thẻ vàng", "Thẻ đen"], c: 2, p: "1" },
      { id: "1-8", q: "Một trận bóng đá chính thức (không tính bù giờ) có bao nhiêu hiệp chính?", a: ["1", "2", "3", "4"], c: 1, p: "1" },
      { id: "1-9", q: "Đội bóng nào có biểu tượng con chim mòng biển?", a: ["Brighton", "Swansea", "Hull", "Fulham"], c: 0, p: "1" },
      { id: "1-10", q: "Cầu thủ nào được gọi là 'Gã Shrek'?", a: ["Rooney", "Scholes", "Giggs", "Neville"], c: 0, p: "1" },
      { id: "1-11", q: "CLB nào có biểu tượng đại bác trên logo?", a: ["Arsenal", "Burnley", "Wolves", "Everton"], c: 0, p: "1" },
      { id: "1-12", q: "HLV Alex Ferguson đã dẫn dắt CLB nào trong 26 năm?", a: ["Chelsea", "Liverpool", "Man Utd", "Man City"], c: 2, p: "1" },
      { id: "1-13", q: "Số áo quen thuộc của Steven Gerrard tại Liverpool?", a: ["7", "8", "9", "10"], c: 1, p: "1" },
      { id: "1-14", q: "Sân nhà của CLB Chelsea tên là gì?", a: ["Stamford Bridge", "Old Trafford", "Villa Park", "Elland Road"], c: 0, p: "1" },
      { id: "1-15", q: "Đội bóng nào được gọi là 'The Kop'?", a: ["Arsenal", "Man Utd", "Liverpool", "Man City"], c: 2, p: "1" },
      { id: "1-16", q: "Vị trí 'CB' trong bóng đá nghĩa là gì?", a: ["Hậu vệ biên", "Trung vệ", "Tiền vệ", "Tiền đạo"], c: 1, p: "1" },
      { id: "1-17", q: "Biệt danh của CLB Leicester City là gì?", a: ["Bầy cáo", "Mèo đen", "Thiên nga", "Đại bàng"], c: 0, p: "1" },
      { id: "1-18", q: "Trận đấu giữa Liverpool và Everton gọi là gì?", a: ["Derby London", "Derby Manchester", "Derby Merseyside", "Derby Bắc Anh"], c: 2, p: "1" },
      { id: "1-19", q: "Biểu tượng của Man Utd có hình gì ở giữa?", a: ["Con gà", "Con quỷ cầm đinh ba", "Pháo", "Sư tử"], c: 1, p: "1" },
      { id: "1-20", q: "Quốc gia nào được coi là nơi khai sinh ra bóng đá hiện đại?", a: ["Brazil", "Anh", "Đức", "Pháp"], c: 1, p: "1" },
],
  2: [
      { id: "2-1", q: "Ai là chân sút vĩ đại nhất lịch sử PL tính đến 2024 (260 bàn)?", a: ["Rooney", "Shearer", "Owen", "Henry"], c: 1, p: "2" },
      { id: "2-2", q: "Biệt danh của Man City là gì?", a: ["The Blues", "The Citizens", "The Toffees", "The Magpies"], c: 1, p: "2" },
      { id: "2-3", q: "HLV Jurgen Klopp đã dẫn dắt đội bóng nào giành chức vô địch năm 2020?", a: ["Arsenal", "Man City", "Liverpool", "Chelsea"], c: 2, p: "2" },
      { id: "2-4", q: "Cầu thủ nào ghi bàn phút 93:20 giúp Man City vô địch năm 2012?", a: ["Aguero", "Dzeko", "Silva", "Kompany"], c: 0, p: "2" },
      { id: "2-5", q: "Số áo huyền thoại của Ronaldo tại Man Utd?", a: ["7", "9", "10", "11"], c: 0, p: "2" },
      { id: "2-6", q: "HLV Arsene Wenger được gọi là 'Giáo sư' vì phong cách gì?", a: ["Trí tuệ & chiến thuật", "Kỷ luật thép", "Gây hấn", "Phòng ngự"], c: 0, p: "2" },
      { id: "2-7", q: "Sân vận động Old Trafford ở thành phố nào?", a: ["London", "Manchester", "Liverpool", "Leeds"], c: 1, p: "2" },
      { id: "2-8", q: "Đội bóng nào vô địch PL mùa giải 2015/16 tạo nên câu chuyện cổ tích?", a: ["Chelsea", "Leicester City", "Man City", "Tottenham"], c: 1, p: "2" },
      { id: "2-9", q: "Cầu thủ nào được gọi là 'Vua Ai Cập' tại Liverpool?", a: ["Elneny", "Salah", "Mane", "Mahrez"], c: 1, p: "2" },
      { id: "2-10", q: "Biệt danh 'Chích chòe' thuộc về đội bóng nào?", a: ["Newcastle", "Wolverhampton", "West Ham", "Leicester"], c: 0, p: "2" },
      { id: "2-11", q: "Harry Kane đã dành phần lớn sự nghiệp tại CLB nào ở PL trước khi sang Đức?", a: ["Arsenal", "Tottenham", "Chelsea", "Liverpool"], c: 1, p: "2" },
      { id: "2-12", q: "Màu áo chính của CLB Man City là gì?", a: ["Xanh dương đậm", "Đỏ", "Xanh thiên thanh", "Vàng"], c: 2, p: "2" },
      { id: "2-13", q: "HLV Jose Mourinho tự nhận mình là ai?", a: ["The Best One", "The Special One", "The Chosen One", "The Only One"], c: 1, p: "2" },
      { id: "2-14", q: "Ai giữ kỷ lục kiến tạo nhiều nhất một mùa giải (20 lần)?", a: ["Ozil", "De Bruyne & Henry", "Fabregas", "Eriksen"], c: 1, p: "2" },
      { id: "2-15", q: "Sân vận động của Arsenal hiện tại tên là gì?", a: ["Highbury", "Emirates", "White Hart Lane", "Etihad"], c: 1, p: "2" },
      { id: "2-16", q: "CLB nào có bài hát truyền thống là 'You'll Never Walk Alone'?", a: ["Man Utd", "Arsenal", "Liverpool", "Chelsea"], c: 2, p: "2" },
      { id: "2-17", q: "Thủ môn nào giữ kỷ lục sạch lưới nhiều nhất lịch sử (202 trận)?", a: ["Schmeichel", "Cech", "Van der Sar", "De Gea"], c: 1, p: "2" },
      { id: "2-18", q: "D. Beckham nổi tiếng nhất với kỹ năng nào?", a: ["Tốc độ", "Đánh đầu", "Tạt bóng", "Xoạc bóng"], c: 2, p: "2" },
      { id: "2-19", q: "Cầu thủ nào có màn ăn mừng kiểu 'Siu'?", a: ["Garnacho", "Ronaldo", "Rashford", "Saka"], c: 1, p: "2" },
      { id: "2-20", q: "Biệt danh của CLB Tottenham Hotspur là gì?", a: ["Gà trống", "Pháo thủ", "Đại bàng", "Mèo đen"], c: 0, p: "2" },
],
  3: [
      { id: "3-1", q: "HLV nào đã dẫn dắt Man Utd giành cú ăn ba năm 1999?", a: ["Busby", "Ferguson", "Moyes", "Ten Hag"], c: 1, p: "4" },
      { id: "3-2", q: "Cầu thủ nào có biệt danh 'Sát thủ có gương mặt trẻ thơ'?", a: ["Rooney", "Solskjaer", "Owen", "Van Nistelrooy"], c: 1, p: "4" },
      { id: "3-3", q: "Ai là 'Vua kiến tạo' tại Man City những mùa gần đây?", a: ["Rodri", "Silva", "De Bruyne", "Foden"], c: 2, p: "4" },
      { id: "3-4", q: "Sân vận động cũ của Tottenham tên là gì?", a: ["White Hart Lane", "Tottenham Hotspur Stadium", "Wembley", "London Stadium"], c: 0, p: "4" },
      { id: "3-5", q: "Biệt danh 'The Cherries' (Quả anh đào) là của đội nào?", a: ["Bournemouth", "Watford", "Burnley", "Southampton"], c: 0, p: "4" },
      { id: "3-6", q: "Thủ môn David De Gea đã dành phần lớn sự nghiệp tại CLB nào ở PL?", a: ["Man City", "Arsenal", "Man Utd", "Chelsea"], c: 2, p: "4" },
      { id: "3-7", q: "Sân vận động St James' Park là sân nhà của đội bóng nào?", a: ["Newcastle", "Sunderland", "Middlesbrough", "Everton"], c: 0, p: "4" },
      { id: "3-8", q: "Cầu thủ ghi bàn nhiều nhất lịch sử Arsenal tại PL (175 bàn)?", a: ["Wright", "Bergkamp", "Henry", "Van Persie"], c: 2, p: "4" },
      { id: "3-9", q: "CLB nào có biệt danh là 'The Toffees'?", a: ["Everton", "Southampton", "Burnley", "Bournemouth"], c: 0, p: "4" },
      { id: "3-10", q: "Đội bóng nào được gọi là 'The Hammers' (Búa tạ)?", a: ["Aston Villa", "West Ham", "Sheffield Utd", "Crystal Palace"], c: 1, p: "4" },
      { id: "3-11", q: "Màu áo truyền thống của CLB Liverpool là gì?", a: ["Xanh dương", "Trắng", "Đỏ", "Vàng"], c: 2, p: "4" },
      { id: "3-12", q: "Cầu thủ lập kỷ lục ghi 5 bàn thắng nhanh nhất lịch sử (20 phút)?", a: ["Berbatov", "Aguero", "Robben", "Zola"], c: 1, p: "4" },
      { id: "3-13", q: "Thủ môn Petr Cech nổi tiếng với chiếc mũ bảo hiểm là người nước nào?", a: ["Séc", "Đức", "Slovakia", "Ba Lan"], c: 0, p: "4" },
      { id: "3-14", q: "CLB nào có biệt danh là 'The Bees' (Những chú ong)?", a: ["Brighton", "Brentford", "Burnley", "Watford"], c: 1, p: "4" },
      { id: "3-15", q: "Sân vận động của CLB Aston Villa có tên là gì?", a: ["Villa Park", "Etihad", "Old Trafford", "Goodison Park"], c: 0, p: "4" },
      { id: "3-16", q: "Thierry Henry giành bao nhiêu danh hiệu PL với Arsenal?", a: ["1", "2", "3", "0"], c: 1, p: "4" },
      { id: "3-17", q: "Biệt danh của CLB Wolverhampton Wanderers là gì?", a: ["Bầy sói", "Bầy cáo", "Những chú đại bàng", "Những chú hổ"], c: 0, p: "4" },
      { id: "3-18", q: "Trận 'Derby Đông Bắc' là cuộc đối đầu giữa Newcastle và đội nào?", a: ["Everton", "Sunderland", "Middlesbrough", "Leeds"], c: 1, p: "4" },
      { id: "3-19", q: "Cầu thủ nào có biệt danh 'Voi rừng'?", a: ["Drogba", "Eto'o", "Zaha", "Pepe"], c: 0, p: "4" },
      { id: "3-20", q: "HLV Pep Guardiola đã giành được bao nhiêu chức vô địch PL tính đến 2024?", a: ["4", "5", "6", "3"], c: 2, p: "4" },
  ],
  4: [
      { id: "4-1", q: "Đội bóng 'Bất bại' (The Invincibles) mùa 2003/04?", a: ["Man Utd", "Chelsea", "Arsenal", "Liverpool"], c: 2, p: "6" },
      { id: "4-2", q: "Đội trưởng dẫn dắt Arsenal mùa giải bất bại 2003/04?", a: ["Henry", "Vieira", "Adams", "Campbell"], c: 1, p: "6" },
      { id: "4-3", q: "Phil Foden đang thi đấu cho CLB nào?", a: ["Arsenal", "Man City", "Man Utd", "Liverpool"], c: 1, p: "6" },
      { id: "4-4", q: "Ai là cầu thủ ghi nhiều hat-trick nhất lịch sử PL (12 lần)?", a: ["Owen", "Aguero", "Yorke", "Henry"], c: 1, p: "6" },
      { id: "4-5", q: "HLV dẫn dắt Everton lâu nhất lịch sử PL?", a: ["Sean Dyche", "Rafael Benítez", "David Moyes", "Carlo Ancelotti"], c: 2, p: "6" },
      { id: "4-6", q: "Biệt danh 'The Bluebirds' thuộc về đội bóng nào?", a: ["Everton", "Cardiff City", "Leicester", "Chelsea"], c: 1, p: "6" },
      { id: "4-7", q: "Cầu thủ châu Á đầu tiên giành Chiếc giày vàng PL?", a: ["Park Ji Sung", "Son Heung Min", "Mitoma", "Kagawa"], c: 1, p: "6" },
      { id: "4-8", q: "HLV Pep Guardiola bắt đầu dẫn dắt Man City năm nào?", a: ["2014", "2015", "2016", "2017"], c: 2, p: "6" },
      { id: "4-9", q: "Thủ môn giành Găng tay vàng mùa 2023/24 là ai?", a: ["Alisson", "Ederson", "David Raya", "Pickford"], c: 2, p: "6" },
      { id: "4-10", q: "Cầu thủ ghi nhiều bàn thắng nhất lịch sử Man Utd?", a: ["Rooney", "Ronaldo", "Charlton", "Best"], c: 0, p: "6" },
      { id: "4-11", q: "CLB nào có linh vật là một chú Sư tử?", a: ["Liverpool", "Aston Villa", "Nottingham Forrest", "Arsenal"], c: 1, p: "6" },
      { id: "4-12", q: "Ai được mệnh danh là 'Đứa con của thần gió'?", a: ["Walcott", "Henry", "Bale", "Mbappe"], c: 1, p: "6" },
      { id: "4-13", q: "Đội bóng nào về đích thứ 2 với số điểm kỷ lục (97 điểm) trong 1 mùa giải PL?", a: ["Liverpool", "Man City", "Arsenal", "Chelsea"], c: 0, p: "6" },
      { id: "4-14", q: "HLV nào đã vô địch PL 13 lần?", a: ["Mourinho", "Ranieri", "Ferguson", "Wenger"], c: 2, p: "6" },
      { id: "4-15", q: "Số áo của đội trưởng Martin Odegaard tại Arsenal hiện tại?", a: ["7", "8", "10", "11"], c: 1, p: "6" },
      { id: "4-16", q: "Chelsea để thủng lưới bao nhiêu bàn mùa 04/05?", a: ["10", "15", "20", "25"], c: 1, p: "6" },
      { id: "4-17", q: "Kevin De Bruyne đến Man City từ CLB nào ở Đức?", a: ["Chelsea", "Wolfsburg", "Dortmund", "Bremen"], c: 1, p: "6" },
      { id: "4-18", q: "Ai là cầu thủ trẻ nhất từng ghi bàn trong lịch sử PL?", a: ["Rooney", "Milner", "James Vaughan", "Fabregas"], c: 2, p: "6" },
      { id: "4-19", q: "Sân vận động Goodison Park là sân nhà cũ của ai?", a: ["Liverpool", "Everton", "Watford", "Luton"], c: 1, p: "6" },
      { id: "4-20", q: "Cầu thủ nào ghi siêu phẩm 'bọ cạp' và nhận giải FIFA Puskas 2017 ?", a: ["Olivier Giroud", "Mkhitaryan", "Lukaku", "Balotelli"], c: 0, p: "6" },
  ],
  5: [
      { id: "5-1", q: "Cầu thủ giữ kỷ lục ra sân nhiều nhất lịch sử PL (653 trận)?", a: ["Ryan Giggs", "Gareth Barry", "James Milner", "Frank Lampard"], c: 1, p: "10" },
      { id: "5-2", q: "Hậu vệ có số đường kiến tạo nhiều nhất lịch sử giải đấu?", a: ["Robertson", "Trent Alexander-Arnold", "Gary Neville", "Ashley Cole"], c: 1, p: "10" },
      { id: "5-3", q: "Cầu thủ ghi bàn nhiều nhất từ chấm đá phạt trực tiếp (18 bàn)?", a: ["Ronaldo", "Ward-Prowse", "Beckham", "Henry"], c: 2, p: "10" },
      { id: "5-4", q: "Thủ môn giữ kỷ lục sạch lưới trong 1 mùa giải (24 trận)?", a: ["Alisson", "Van der Sar", "Petr Cech", "De Gea"], c: 2, p: "10" },
      { id: "5-5", q: "CLB nào có biệt danh là 'The Cottagers'?", a: ["Fulham", "Burnley", "Watford", "Luton"], c: 0, p: "10" },
      { id: "5-6", q: "Cầu thủ ghi nhiều bàn nhất ngay mùa đầu tiên đến PL (36 bàn)?", a: ["Haaland", "Salah", "Cole", "Phillips"], c: 0, p: "10" },
      { id: "5-7", q: "Cầu thủ ghi 4 bàn thằng trong 12 phút kể từ khi vào sân từ ghế dự bị?", a: ["Jermain Defoe", "Peter Crouch", "Ole Gunnar Solskjaer", "Olivier Giroud"], c: 2, p: "10" },
      { id: "5-8", q: "Ai là cầu thủ ghi bàn thắng nhanh nhất lịch sử PL (7.69 giây)?", a: ["Shane Long", "Ledley King", "Alan Smith", "Christian Eriksen"], c: 0, p: "10" },
      { id: "5-9", q: "Cầu thủ nhận nhiều thẻ vàng nhất lịch sử giải đấu (123 thẻ)?", a: ["Rooney", "Gareth Barry", "Kevin Davies", "Lee Cattermole"], c: 1, p: "10" },
      { id: "5-10", q: "HLV có tỷ lệ thắng cao nhất lịch sử Premier League?", a: ["Alex Ferguson", "Pep Guardiola", "Jurgen Klopp", "Jose Mourinho"], c: 1, p: "10" },
      { id: "5-11", q: "Số điểm thấp nhất của 1 đội bóng trong 1 mùa giải (Derby County)?", a: ["9 điểm", "11 điểm", "13 điểm", "15 điểm"], c: 1, p: "10" },
      { id: "5-12", q: "Cầu thủ ghi bàn trong 11 trận liên tiếp tại PL?", a: ["Jamie Vardy", "Van Nistelrooy", "Haaland", "Salah"], c: 0, p: "10" },
      { id: "5-13", q: "Đội bóng nào có biệt danh là 'The Tigers' (Những chú hổ)?", a: ["Hull City", "Wolverhampton", "Leicester", "Brentford"], c: 0, p: "10" },
      { id: "5-14", q: "Sân vận động của CLB Brighton có tên là gì?", a: ["Amex Stadium", "Vitality Stadium", "Kenilworth Road", "Craven Cottage"], c: 0, p: "10" },
      { id: "5-15", q: "Ai là cầu thủ đầu tiên ghi 5 bàn trong một trận đấu PL?", a: ["Andrew Cole", "Jimmy Hasselbaink", "Dimitar Berbatov", "Sergio Aguero"], c: 0, p: "10" },
      { id: "5-16", q: "Biệt danh 'The Toffees' của Everton liên quan đến cửa hàng gì gần sân vận động?", a: ["Cửa hàng kẹo", "Cửa hàng bánh mỳ", "Cửa hàng quần áo", "Cửa hàng dụng cụ"], c: 0, p: "10" },
      { id: "5-17", q: "Cầu thủ ghi nhiều bàn thắng nhất bằng đầu lịch sử PL?", a: ["Peter Crouch", "Duncan Ferguson", "Oliver Giroud", "Christian Benteke"], c: 0, p: "10" },
      { id: "5-18", q: "HLV Carlo Ancelotti từng vô địch PL cùng đội bóng nào?", a: ["Everton", "Chelsea", "Man City", "Man Utd"], c: 1, p: "10" },
      { id: "5-19", q: "CLB nào biệt hiệu là 'những chú đại bàng'?", a: ["Crystal Palace", "West Ham", "Millwall", "Charlton"], c: 0, p: "10" },
      { id: "5-20", q: "Cầu thủ kiến tạo nhiều nhất lịch sử (162 kiến tạo)?", a: ["Cesc Fabregas", "Frank Lampard", "Ryan Giggs", "Wayne Rooney"], c: 2, p: "10" },
  ],
  6: [
      { id: "6-1", q: "Đội duy nhất đạt cột mốc 100 điểm trong một mùa giải?", a: ["Liverpool", "Chelsea", "Man City", "Arsenal"], c: 2, p: "15" },
      { id: "6-2", q: "Cầu thủ lập hat-trick nhanh nhất lịch sử (2 phút 56 giây)?", a: ["Sadio Mane", "Robbie Fowler", "Gabriel Jesus", "Raheem Sterling"], c: 0, p: "15" },
      { id: "6-3", q: "HLV huyền thoại Arsene Wenger là người nước nào?", a: ["Anh", "Đức", "Pháp", "Bỉ"], c: 2, p: "15" },
      { id: "6-4", q: "Thủ môn duy nhất giành giải 'Cầu thủ xuất sắc nhất mùa' (do BTC trao)?", a: ["Schmeichel", "Petr Cech", "Van der Sar", "Alisson"], c: 0, p: "15" },
      { id: "6-5", q: "Cầu thủ ghi nhiều bàn nhất từ chấm penalty (56 bàn)?", a: ["Frank Lampard", "Alan Shearer", "Steven Gerrard", "Crespo"], c: 1, p: "15" },
      { id: "6-6", q: "Biệt danh của CLB Sheffield United là gì?", a: ["The Blades", "The Owls", "The Tigers", "The Lions"], c: 0, p: "15" },
      { id: "6-7", q: "Cầu thủ có biệt danh 'The Iceman' tại Arsenal?", a: ["Thierry Henry", "Dennis Bergkamp", "Robert Pires", "Patrick Vieira"], c: 1, p: "15" },
      { id: "6-8", q: "Sân vận động của CLB Southampton có tên là gì?", a: ["St Mary's", "Fratton Park", "The Den", "Vicarage Road"], c: 0, p: "15" },
      { id: "6-9", q: "Cầu thủ phản lưới nhà nhiều nhất lịch sử PL (10 bàn)?", a: ["Jamie Carragher", "Richard Dunne", "Martin Skrtel", "Phil Jones"], c: 1, p: "15" },
      { id: "6-10", q: "Đội bóng nào có biệt danh 'The Villans'?", a: ["Aston Villa", "West Ham", "Everton", "Wolves"], c: 0, p: "15" },
      { id: "6-11", q: "Người ghi bàn thắng đầu tiên trong lịch sử Premier League năm 1992?", a: ["Les Ferdinand", "Brian Deane", "Teddy Sheringham", "Eric Cantona"], c: 1, p: "15" },
      { id: "6-12", q: "HLV Claudio Ranieri (vô địch cùng Leicester) có biệt danh là gì?", a: ["Giáo sư", "Gã thợ hàn", "Gã đồ tể", "Pháp sư"], c: 1, p: "15" },
      { id: "6-13", q: "Ai ghi 5 hat-trick trong một mùa giải duy nhất (1995/96)?", a: ["Alan Shearer", "Sheringham", "Erling Haaland", "Sergio Aguero"], c: 0, p: "15" },
      { id: "6-14", q: "CLB nào có biểu tượng hai chiếc búa đan chéo nhau?", a: ["Sheffield Utd", "West Ham", "Burnley", "Stoke City"], c: 1, p: "15" },
      { id: "6-15", q: "Thủ môn giữ sạch lưới liên tiếp lâu nhất lịch sử (14 trận)?", a: ["Petr Cech", "Edwin van der Sar", "David James", "Pepe Reina"], c: 1, p: "15" },
      { id: "6-16", q: "Cầu thủ đoạt giải 'Bàn thắng đẹp nhất 20 năm PL' (xe đạp chổng ngược)?", a: ["Rooney", "Berbatov", "Garnacho", "Benteke"], c: 0, p: "15" },
      { id: "6-17", q: "Cầu thủ có số lần vào sân thay người rồi ghi bàn nhiều nhất (24 bàn)?", a: ["Solskjaer", "Jermain Defoe", "Olivier Giroud", "Nwankwo Kanu"], c: 1, p: "15" },
      { id: "6-18", q: "Ai đoạt Quả bóng vàng 2024?", a: ["Vinicius", "Rodri", "Bellingham", "Haaland"], c: 1, p: "15" },
      { id: "6-19", q: "Cầu thủ từng đá cho cả 3 CLB: Liverpool, Real Madrid và Man Utd?", a: ["David Beckham", "Michael Owen", "Cristiano Ronaldo", "Steve McManaman"], c: 1, p: "15" },
      { id: "6-20", q: "Đội bóng nào được mệnh danh là 'Những chú thiên nga'?", a: ["Swansea", "Cardiff", "Everton", "Watford"], c: 0, p: "15" },
],
  7: [
      { id: "7-1", q: "Trận Derby Bắc London là cuộc đối đầu giữa Arsenal và đội nào?", a: ["Chelsea", "Tottenham", "West Ham", "Crystal Palace"], c: 1, p: "25" },
      { id: "7-2", q: "Ai ghi nhiều bàn thắng nhất trong các trận Derby Bắc London?", a: ["Henry", "Harry Kane", "Pires", "Adebayor"], c: 1, p: "25" },
      { id: "7-3", q: "Trận 'Derby nước Anh' (North West Derby) diễn ra giữa?", a: ["Man Utd & Man City", "Man Utd & Liverpool", "Liverpool & Everton", "Arsenal & Chelsea"], c: 1, p: "25" },
      { id: "7-4", q: "Đội bóng nào bất bại 49 trận liên tiếp ở PL?", a: ["Man City", "Man Utd", "Arsenal", "Chelsea"], c: 2, p: "25" },
      { id: "7-5", q: "HLV dẫn dắt Chelsea vô địch PL ngay mùa đầu tiên (2004/05)?", a: ["Ancelotti", "Mourinho", "Conte", "Ranieri"], c: 1, p: "25" },
      { id: "7-6", q: "Cầu thủ ghi bàn nhiều nhất lịch sử Chelsea tại PL?", a: ["Drogba", "Lampard", "Hazard", "Terry"], c: 1, p: "25" },
      { id: "7-7", q: "HLV người Scotland nào đã vô địch PL cùng Blackburn Rovers?", a: ["Ferguson", "Kenny Dalglish", "David Moyes", "George Graham"], c: 1, p: "25" },
      { id: "7-8", q: "Cole Palmer chuyển đến Chelsea từ đội nào?", a: ["Liverpool", "Man City", "Leicester", "Arsenal"], c: 1, p: "25" },
      { id: "7-9", q: "Cầu thủ giữ kỷ lục nhận nhiều thẻ đỏ nhất lịch sử (8 thẻ)?", a: ["Vieira", "Duncan Ferguson", "Richard Dunne", "Cả 3 người trên"], c: 3, p: "25" },
      { id: "7-10", q: "Trận Derby West Midlands diễn ra giữa Aston Villa và?", a: ["Birmingham City", "Wolves", "West Brom", "Leicester"], c: 0, p: "25" },
      { id: "7-11", q: "Cầu thủ đầu tiên đạt mốc 200 bàn thắng tại PL?", a: ["Wayne Rooney", "Alan Shearer", "Harry Kane", "Smicer"], c: 1, p: "25" },
      { id: "7-12", q: "Thủ môn đầu tiên ghi bàn tại PL?", a: ["Seaman", "Schmeichel", "Howard", "Cudicini"], c: 1, p: "35" },
      { id: "7-13", q: "Cầu thủ kiến tạo nhiều nhất cho một CLB duy nhất (162 lần)?", a: ["Ryan Giggs", "Paul Scholes", "Steven Gerrard", "Frank Lampard"], c: 0, p: "25" },
      { id: "7-14", q: "Sân nhà của CLB West Ham hiện tại là sân nào?", a: ["Upton Park", "London Stadium", "The O2", "Wembley"], c: 1, p: "25" },
      { id: "7-15", q: "Cầu thủ ghi bàn ở 7 CLB khác nhau tại PL?", a: ["Anelka", "Bellamy", "Marcus Bent", "Crouch"], c: 2, p: "25" },
      { id: "7-16", q: "Biệt danh 'The Hatters' (Thợ làm mũ) là của đội nào?", a: ["Luton Town", "Reading", "Huddersfield", "Bolton"], c: 0, p: "25" },
      { id: "7-17", q: "Ai ghi bàn, kiến tạo và phản lưới trong cùng 1 trận đấu?", a: ["Gareth Bale", "Wayne Rooney", "Kevin Davies", "Cả 3 người trên"], c: 3, p: "25" },
      { id: "7-18", q: "Cầu thủ nào có biệt danh 'thần chết'?", a: ["René Higuita", "Aaron Ramsey", "Lee Cattermole", "Hulk"], c: 1, p: "25" },
      { id: "7-19", q: "Cầu thủ ghi bàn nhiều nhất lịch sử Man City tại PL?", a: ["Sergio Aguero", "Sterling", "De Bruyne", "Yaya Toure"], c: 0, p: "25" },
      { id: "7-20", q: "Sân vận động của CLB Sheffield United tên là gì?", a: ["Hillsborough", "Bramall Lane", "Elland Road", "Turf Moor"], c: 1, p: "25" },
  ],
  8: [
      { id: "8-1", q: "Bản hợp đồng đắt giá nhất lịch sử Arsenal tính đến hết mùa 23/24?", a: ["Nicolas Pepe", "Declan Rice", "Kai Havertz", "Bukayo Saka"], c: 1, p: "35" },
      { id: "8-2", q: "Ai là cầu thủ duy nhất giành 4 danh hiệu Chiếc giày vàng PL?", a: ["Ruud van Nistelrooy", "Thierry Henry", "Harry Kane", "Mohamed Salah"], c: 1, p: "35" },
      { id: "8-3", q: "HLV người Ý đầu tiên vô địch Premier League là ai?", a: ["Roberto Mancini", "Carlo Ancelotti", "Claudio Ranieri", "Antonio Conte"], c: 1, p: "35" },
      { id: "8-4", q: "SVĐ nào có sức chứa lớn nhất Premier League?", a: ["Emirates", "Tottenham", "Old Trafford", "London"], c: 2, p: "35" },
      { id: "8-5", q: "Cầu thủ nào ghi nhiều bàn nhất trong lịch sử các trận mở màn (9 bàn)?", a: ["Wayne Rooney", "Mohamed Salah", "Frank Lampard", "R. Pires"], c: 1, p: "35" },
      { id: "8-6", q: "Sân vận động Molineux là sân nhà của đội bóng nào?", a: ["Wolves", "West Brom", "Stoke City", "Walsall"], c: 0, p: "35" },
      { id: "8-7", q: "Thủ môn nào giữ kỷ lục nhận nhiều thẻ đỏ nhất PL (3 thẻ)?", a: ["Jens Lehmann", "Pavel Srnicek", "Shaka Hislop", "Cả 3 người trên"], c: 3, p: "35" },
      { id: "8-8", q: "Cầu thủ đạt mốc 100 bàn thắng nhanh nhất lịch sử PL (104 trận))?", a: ["Erling Haaland", "Alan Shearer", "Ronaldo", "Sergio Aguero"], c: 0, p: "35" },
      { id: "8-9", q: "Đội bóng nào có biệt danh 'The Saints'?", a: ["Wigan Athletic", "Southampton", "Sheffield United", "Blackburn"], c: 1, p: "35" },
      { id: "8-10", q: "Con số kiến tạo nhiều bàn thắng nhất trong một trận đấu tại PL là bao nhiêu?", a: ["3 lần", "4 lần", "5 lần", "6 lần"], c: 1, p: "35" },
      { id: "8-11", q: "CLB duy nhất vô địch PL mà không lọt Top 4 ở mùa giải ngay trước đó?", a: ["Leicester City", "Man Utd", "Chelsea", "Blackburn Rovers"], c: 0, p: "35" },
      { id: "8-12", q: "Sân vận động của CLB Bournemouth tên là gì?", a: ["Vitality Stadium", "Amex Stadium", "St Mary's", "Kenilworth Road"], c: 0, p: "35" },
      { id: "8-13", q: "Cầu thủ nào ghi bàn phản lưới nhà nhanh nhất lịch sử PL?", a: ["Mickael Silvestre", "Jamie Carragher", "Antolin Alcaraz", "Chris Brass"], c: 2, p: "35" },
      { id: "8-14", q: "Ai là cầu thủ đầu tiên ghi bàn trong 7 trận mở màn liên tiếp?", a: ["Wayne Rooney", "Mohamed Salah", "Sergio Aguero", "Jamie Vardy"], c: 1, p: "35" },
      { id: "8-15", q: "CLB nào có biệt danh 'The Trotters'?", a: ["Bolton Wanderers", "Charlton", "Fulham", "Derby"], c: 0, p: "35" },
      { id: "8-16", q: "Cầu thủ nào ghi nhiều bàn thắng nhất từ ngoài vòng cấm (41 bàn)?", a: ["David Beckham", "Frank Lampard", "Steven Gerrard", "Steven McManaman"], c: 1, p: "35" },
      { id: "8-17", q: "Ai là HLV dẫn dắt nhiều trận nhất lịch sử Premier League (828 trận)?", a: ["Alex Ferguson", "Arsene Wenger", "Harry Redknapp", "David Moyes"], c: 1, p: "35" },
      { id: "8-18", q: "Đội bóng nào có sân nhà tên là King Power?", a: ["Leicester City", "Reading", "Derby", "Hull City"], c: 0, p: "35" },
      { id: "8-19", q: "Cầu thủ có số trận hòa nhiều nhất lịch sử giải đấu?", a: ["Gareth Barry", "James Milner", "Frank Lampard", "Ryan Giggs"], c: 0, p: "35" },
      { id: "8-20", q: "Bàn thắng thứ 20.000 của Premier League được ghi bởi ai?", a: ["Marc Albrighton", "Moritz Volz", "Zlatan Ibrahimovic", "Les Ferdinand"], c: 0, p: "35" },
  ],
  9: [
      { id: "9-1", q: "Mùa giải Premier League đầu tiên (1992/93) có bao nhiêu đội?", a: ["18", "20", "22", "24"], c: 2, p: "50" },
      { id: "9-2", q: "Thủ môn giữ kỷ lục cản phá nhiều quả phạt đền nhất lịch sử Premier League (13 lần)?", a: ["David James", "Petr Cech", "Shay Given", "Robert Green"], c: 0, p: "50" },
      { id: "9-3", q: "Cầu thủ nước ngoài đầu tiên đạt mốc 100 bàn thắng?", a: ["Henry", "Cantona", "Van Nistelrooy", "Dwight Yorke"], c: 3, p: "50" },
      { id: "9-4", q: "CLB giữ kỷ lục thắng nhiều trận nhất một mùa (32 trận)?", a: ["Liverpool", "Man City", "Cả 2 đội trên", "Chelsea"], c: 2, p: "50" },
      { id: "9-5", q: "Thủ môn giữ kỷ lục sạch lưới liên tiếp lâu nhất PL (1.311 phút)?", a: ["Cech", "Edwin van der Sar", "Reina", "De Gea"], c: 1, p: "50" },
      { id: "9-6", q: "HLV nước ngoài đầu tiên giành chức vô địch Premier League?", a: ["Wenger", "Mourinho", "Ferguson", "Kenny Dalglish"], c: 0, p: "50" },
      { id: "9-7", q: "Cầu thủ nhận giải 'Cầu thủ xuất sắc nhất tháng' nhiều nhất (8 lần)?", a: ["Gerrard", "Harry Kane", "Aguero", "Rashford"], c: 1, p: "50" },
      { id: "9-8", q: "Sân vận động Highbury là sân nhà cũ của đội bóng nào?", a: ["Arsenal", "Tottenham", "Chelsea", "West Ham"], c: 0, p: "50" },
      { id: "9-9", q: "Hệ thống VAR (Video Hỗ trợ Trọng tài) lần đầu được áp dụng tại PL mùa nào?", a: ["18/19", "19/20", "20/21", "21/22"], c: 1, p: "50" },
      { id: "9-10", q: "Cầu thủ ghi nhiều bàn nhất mà không có quả penalty nào?", a: ["Les Ferdinand", "Andrew Cole", "Mane", "Crouch"], c: 1, p: "50" },
      { id: "9-11", q: "Thủ môn duy nhất ghi bàn từ đá phạt trực tiếp ở PL?", a: ["Schmeichel", "Begovic", "Paul Robinson", "Brad Friedel"], c: 2, p: "50" },
      { id: "9-12", q: "Hậu vệ ghi nhiều bàn thắng nhất lịch sử Premier League (41 bàn)?", a: ["John Terry", "David Unsworth", "Leighton Baines", "Gary Pallister"], c: 0, p: "50" },
      { id: "9-13", q: "Trọng tài rút nhiều thẻ đỏ nhất lịch sử PL?", a: ["Howard Webb", "Mike Dean", "Atkinson", "Clattenburg"], c: 1, p: "50" },
      { id: "9-14", q: "HLV từng dẫn dắt nhiều CLB tại Premier League nhất lịch sử (9 CLB)?", a: ["Harry Redknapp", "Sam Allardyce", "Mark Hughes", "Roy Hodgson"], c: 1, p: "50" },
      { id: "9-15", q: "Đội bóng thủng lưới ít nhất một mùa giải (15 bàn)?", a: ["Man Utd", "Arsenal", "Chelsea", "Man City"], c: 2, p: "50" },
      { id: "9-16", q: "Sân vận động Elland Road là của đội nào?", a: ["Leeds United", "Sheffield Utd", "Hull City", "Middlesbrough"], c: 0, p: "50" },
      { id: "9-17", q: "Ai ghi nhiều hat-trick nhất lịch sử PL?", a: ["M. Baros", "Aguero", "Alnelka", "Henry"], c: 1, p: "50" },
      { id: "9-18", q: "Cầu thủ đoạt PFA xuất sắc nhất 3 lần?", a: ["Henry", "Ronaldo", "De Bruyne", "Chưa có ai"], c: 3, p: "50" },
      { id: "9-19", q: "CLB nào có biệt danh là 'The Black Cats' (Mèo đen)?", a: ["Sunderland", "Swansea", "Stoke", "Southampton"], c: 0, p: "50" },
      { id: "9-20", q: "Cầu thủ ghi nhiều bàn nhất lịch sử ĐT Anh khi chơi tại PL?", a: ["Rooney", "Harry Kane", "Sheringham", "Owen"], c: 1, p: "50" },
  ],
  10: [
      { id: "10-1", q: "Đội bóng nào đã trụ hạng thành công với điểm số thấp nhất (32 điểm) trong một mùa?", a: ["West Brom", "Nottingham Forest", "Wigan", "Sunderland"], c: 1, p: "70" },
      { id: "10-2", q: "Cầu thủ trẻ nhất từng ra sân tại Premier League?", a: ["Elliott", "Ethan Nwaneri", "Fabregas", "Lennon"], c: 1, p: "70" },
      { id: "10-3", q: "Cầu thủ ghi bàn thắng muộn nhất lịch sử PL (phút 101:48)?", a: ["Oli McBurnie", "Kuyt", "Jesus", "Palmer"], c: 0, p: "70" },
      { id: "10-4", q: "Thủ môn duy nhất ghi bàn trực tiếp từ một tình huống phạt góc?", a: ["Begovic", "Schmeichel", "Alisson Becker", "Friedel"], c: 2, p: "70" },
      { id: "10-5", q: "HLV nhận nhiều giải 'HLV của tháng' nhất lịch sử (27 lần)?", a: ["Wenger", "Alex Ferguson", "Guardiola", "Moyes"], c: 1, p: "70" },
      { id: "10-6", q: "CLB Man City giành được bao nhiêu danh hiệu PL liên tiếp?", a: ["2", "3", "4", "5"], c: 2, p: "70" },
      { id: "10-7", q: "Cầu thủ giữ kỷ lục thi đấu cho nhiều CLB tại Premier League nhất (8 đội bóng)?", a: ["Peter Crouch", "Marcus Bent", "Nicolas Anelka", "Craig Bellamy"], c: 1, p: "70" },
      { id: "10-8", q: "Ai là cầu thủ đầu tiên ghi bàn trong mọi phút từ 1 đến 90 tại PL?", a: ["Ronaldo", "Matt Le Tissier", "Rooney", "Chưa có ai"], c: 3, p: "70" },
      { id: "10-9", q: "CLB giữ kỷ lục thua nhiều trận liên tiếp nhất tại PL (20 trận)?", a: ["Derby County", "Sunderland", "Norwich", "Sheffield Utd"], c: 1, p: "70" },
      { id: "10-10", q: "Mùa giải Shearer lập kỷ lục 5 hat-trick, ông đá cho đội nào?", a: ["Blackburn", "Newcastle", "Southampton", "Leicester"], c: 0, p: "70" },
      { id: "10-11", q: "Cầu thủ ghi bàn thắng thứ 30.000 của Premier League?", a: ["Chris Wood", "Albrighton", "Ibrahimovic", "Volz"], c: 0, p: "70" },
      { id: "10-12", q: "HLV tại vị lâu nhất một CLB tại PL (26 năm)?", a: ["Arsene Wenger", "Alex Ferguson", "David Moyes", "Joe Kinnear"], c: 1, p: "70" },
      { id: "10-13", q: "Cầu thủ đạt mốc 100 kiến tạo với số trận ít nhất (237 trận)?", a: ["Fabregas", "Kevin De Bruyne", "Giggs", "Ozil"], c: 1, p: "70" },
      { id: "10-14", q: "CLB có sân vận động tên là The Hawthorns?", a: ["West Brom", "Blackpool", "Bolton", "Reading"], c: 0, p: "70" },
      { id: "10-15", q: "Kỷ lục thắng cách biệt lớn nhất (9-0) được nắm giữ bởi mấy đội?", a: ["1", "2", "3", "4"], c: 2, p: "70" },
      { id: "10-16", q: "Đội bóng đầu tiên vô địch Premier League 2 mùa liên tiếp?", a: ["Arsenal", "Chelsea", "Man Utd", "Man City"], c: 2, p: "70" },
      { id: "10-17", q: "Số lượng khán giả đông nhất lịch sử một trận đấu PL?", a: ["75.000", "83.222", "90.000", "60.000"], c: 1, p: "70" },
      { id: "10-18", q: "Cầu thủ duy nhất ghi hat-trick chỉ bằng đầu trong 1 trận?", a: ["Duncan Ferguson", "Salomon Rondon", "Peter Crouch", "Tim Cahill"], c: 1, p: "70" },
      { id: "10-19", q: "Đội bóng nắm giữ kỷ lục hòa nhiều trận nhất một mùa (17 trận)?", a: ["Aston Villa", "Newcastle", "Cả 2 đội trên", "Sunderland"], c: 2, p: "70" },
      { id: "10-20", q: "Cầu thủ ghi bàn cuối cùng tại sân cũ Highbury của Arsenal?", a: ["Thierry Henry", "Pires", "Bergkamp", "Van Persie"], c: 0, p: "70" },
  ],
  11: [
      { id: "11-1", q: "HLV Mourinho lần đầu đến PL năm nào?", a: ["2002", "2003", "2004", "2005"], c: 2, p: "85" },
      { id: "11-2", q: "Cầu thủ ghi hat-trick vào lưới cùng 1 đội 3 mùa liên tiếp?", a: ["Shearer", "Luis Suarez", "Aguero", "Haaland"], c: 1, p: "85" },
      { id: "11-3", q: "CLB giữ kỷ lục chuỗi trận bất bại trên sân nhà dài nhất (86 trận)?", a: ["Man Utd", "Man City", "Chelsea", "Liverpool"], c: 2, p: "85" },
      { id: "11-4", q: "Thủ môn giữ kỷ lục có số lần kiến tạo nhiều nhất (5 lần)?", a: ["Schmeichel", "Paul Robinson", "Seaman", "Reina"], c: 1, p: "85" },
      { id: "11-5", q: "Cầu thủ kiến tạo 4 bàn trong 1 hiệp?", a: ["Kane", "Tadic", "Reyes", "Cả 3 người"], c: 3, p: "85" },
      { id: "11-6", q: "Ai ghi nhiều bàn nhất trong một trận sân khách (4 bàn)?", a: ["Solskjaer", "Harry Kane", "Tất cả đều đúng", "Arshavin"], c: 2, p: "85" },
      { id: "11-7", q: "HLV vô địch Premier League sớm nhất (sau 31 vòng)?", a: ["Ferguson", "Guardiola", "Jurgen Klopp", "Mourinho"], c: 2, p: "85" },
      { id: "11-8", q: "Cầu thủ ghi bàn ở nhiều sân vận động khác nhau nhất (26 sân)?", a: ["Rooney", "Fredrik Ljungberg", "Harry Kane", "Lampard"], c: 2, p: "85" },
      { id: "11-9", q: "Đội bóng thắng cách biệt lớn nhất trên sân khách (0-9)?", a: ["Man Utd", "Leicester City", "Liverpool", "Man City"], c: 1, p: "85" },
      { id: "11-10", q: "Ai nhận thẻ vàng trong mọi mùa giải họ tham dự (21 mùa)?", a: ["Barry", "Ryan Giggs", "Scholes", "Milner"], c: 1, p: "85" },
      { id: "11-11", q: "Cầu thủ ghi bàn trong nhiều trận chung kết FA Cup nhất?", a: ["Didier Drogba", "Lampard", "Ian Wright", "Rooney"], c: 0, p: "85" },
      { id: "11-12", q: "CLB duy nhất bị xuống hạng dù giành được 42 điểm trong 1 mùa giải?", a: ["West Ham", "Bolton", "Sunderland", "Newcastle"], c: 0, p: "85" },
      { id: "11-13", q: "Ai ghi bàn đầu tiên cho Arsenal tại sân Emirates?", a: ["Henry", "Gilberto Silva", "Van Persie", "Fabregas"], c: 1, p: "85" },
      { id: "11-14", q: "Trọng tài rút thẻ đỏ nhanh nhất lịch sử PL (giây thứ 47)?", a: ["Friend", "Mike Dean", "Mark Halsey", "David Elleray"], c: 3, p: "85" },
      { id: "11-15", q: "Cầu thủ giữ kỷ lục về số lần việt vị nhiều nhất giải?", a: ["Adebayor", "Jermain Defoe", "Agbonlahor", "Anelka"], c: 1, p: "85" },
      { id: "11-16", q: "HLV duy nhất vô địch PL mà trước đó là cầu thủ của chính CLB đó?", a: ["Kenny Dalglish", "Ferguson", "Guardiola", "Arteta"], c: 0, p: "85" },
      { id: "11-17", q: "Mùa giải cuối cùng có 22 đội tham dự PL trước khi rút xuống 20 đội?", a: ["92/93", "93/94", "94/95", "95/96"], c: 2, p: "85" },
      { id: "11-18", q: "Đội bóng giữ sạch lưới nhiều nhất một mùa giải (25 trận)?", a: ["Man Utd", "Arsenal", "Chelsea", "Liverpool"], c: 2, p: "85" },
      { id: "11-19", q: "Trận đấu có số bàn thắng nhiều nhất lịch sử PL là trận nào?", a: ["Portsmouth 7-4 Reading", "Man Utd 9-0 Soton", "Tottenham 9-1 Wigan", "Man City 8-0 Watford"], c: 0, p: "85" },
      { id: "11-20", q: "Bàn thắng nhanh nhất lịch sử Premier League ghi ở giây thứ mấy?", a: ["7.69", "9.11", "10.2", "8.5"], c: 0, p: "85" },
],
  12: [
      { id: "12-1", q: "Đội bóng nào vô địch nhưng không có bất kỳ cầu thủ nào trong đội hình hình tiêu biểu của mùa giải?", a: ["Man Utd", "Blackburn", "Aston Villa", "Norwich"], c: 0, p: "100" },
      { id: "12-2", q: "Ai giành HLV xuất sắc nhất năm 3 lần liên tiếp?", a: ["Ferguson", "Pep Guardiola", "Mourinho", "Wenger"], c: 1, p: "100" },
      { id: "12-3", q: "Cầu thủ duy nhất ghi bàn vào lưới 39 đội bóng khác nhau tại PL?", a: ["Rooney", "Frank Lampard", "Van Persie", "Harry Kewell"], c: 1, p: "100" },
      { id: "12-4", q: "Ai ghi hat-trick trong 2 trận liên tiếp vào lưới cùng 1 thủ môn?", a: ["Zaha", "Aguero", "Luis Suarez", "Haaland"], c: 2, p: "100" },
      { id: "12-5", q: "Ai ghi bàn trong 21 mùa giải Premier League liên tiếp?", a: ["Gareth Barry", "Ryan Giggs", "Scholes", "Lampard"], c: 1, p: "100" },
      { id: "12-6", q: "Thủ môn giữ sạch lưới nhiều nhất trên sân khách?", a: ["Petr Cech", "De Gea", "Reina", "Van der Sar"], c: 0, p: "100" },
      { id: "12-7", q: "Chuỗi trận thắng liên tiếp dài nhất lịch sử (18 trận)?", a: ["Man City", "Liverpool", "Cả 2 đội trên", "Arsenal"], c: 2, p: "100" },
      { id: "12-8", q: "Ai là cầu thủ trẻ nhất từng đeo băng thủ quân tại PL?", a: ["Fabregas", "Gareth Barry", "Ray Wilkins", "Tony Adams"], c: 1, p: "100" },
      { id: "12-9", q: "Ai ghi 5 bàn một trận mà không có quả penalty nào?", a: ["Andrew Cole", "Asley Cole", "Cole Palmer", "Carlton Cole"], c: 0, p: "100" },
      { id: "12-10", q: "CLB giành nhiều điểm nhất trên sân khách một mùa (50 điểm)?", a: ["Man City", "Liverpool", "Chelsea", "Man Utd"], c: 0, p: "100" },
      { id: "12-11", q: "Cầu thủ lập nhiều hattrick hoàn hảo (ghi bàn bằng chân trái, chân phải, đầu) nhất tại PL?", a: ["Raheem Sterling", "Yakubu", "Erling Haaland", "Robbie Fowler"], c: 3, p: "100" },
      { id: "12-12", q: "Cầu thủ ghi bàn nhiều nhất lịch sử cho các CLB London?", a: ["Henry", "Harry Kane", "Lampard", "Sheringham"], c: 1, p: "100" },
      { id: "12-13", q: "HLV vô địch PL với số cầu thủ sử dụng ít nhất (19 người)?", a: ["Claudio Ranieri", "Mourinho", "Ferguson", "Conte"], c: 0, p: "100" },
      { id: "12-14", q: "Chuỗi trận giữ sạch lưới dài nhất lịch sử (14 trận)?", a: ["Chelsea", "Man Utd", "Arsenal", "Man City"], c: 1, p: "100" },
      { id: "12-15", q: "Cặp bài trùng Kane và Son Heung-min đã kiến tạo cho nhau bao nhiêu bàn?", a: ["36", "40", "47", "50"], c: 2, p: "100" },
      { id: "12-16", q: "Cầu thủ ghi bàn đầu tiên cho Man Utd tại giải Premier League?", a: ["Mark Hughes", "Cantona", "Giggs", "Ince"], c: 0, p: "100" },
      { id: "12-17", q: "Ai nhận 3 thẻ đỏ trong một mùa giải duy nhất?", a: ["Dion Dublin", "Vinnie Jones", "Cả 2 người trên", "Cattermole"], c: 2, p: "100" },
      { id: "12-18", q: "Trận đấu có nhiều thẻ vàng nhất lịch sử (14 thẻ) tính đến năm 2024?", a: ["Chelsea vs Spurs (2016)", "MU vs Arsenal (2003)", "Bournemouth vs Chelsea (2024)", "Tottenham vs Sheffield Utd (2023)"], c: 2, p: "100" },
      { id: "12-19", q: "Có cầu thủ nào ghi bàn ở Premier League trong 4 thập kỷ khác nhau?", a: ["Giggs", "James Milner", "Gareth Barry", "Chưa có ai"], c: 3, p: "100" },
      { id: "12-20", q: "Những đội bóng nào chưa từng xuống hạng kể từ năm 1992?", a: ["Everton", "6 đội: ARS, CHE, EVE, LIV, MU, TOT", "Man City & MU", "Chỉ có Arsenal"], c: 1, p: "100" },
  ],
};

export const SOUNDS: SoundEffect[] = [
  // Intro removed here to be handled by synthesizer
  { id: 'whistle', src: 'https://assets.mixkit.co/active_storage/sfx/2043/2043-preview.mp3' },
  { id: 'correct', src: 'https://assets.mixkit.co/active_storage/sfx/2000/2000-preview.mp3' },
  { id: 'wrong', src: 'https://assets.mixkit.co/active_storage/sfx/2013/2013-preview.mp3' },
  { id: 'win', src: 'https://assets.mixkit.co/active_storage/sfx/1435/1435-preview.mp3' },
  { id: 'thinking', src: 'https://assets.mixkit.co/active_storage/sfx/2568/2568-preview.mp3' },
  { id: 'cash', src: 'https://assets.mixkit.co/active_storage/sfx/2019/2019-preview.mp3' },
  { id: 'substitute', src: 'https://assets.mixkit.co/active_storage/sfx/2578/2578-preview.mp3' },
];
